# Generated by Django 4.0.4 on 2022-06-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
